### ISSUE TITLE
Как изменить голосовой движок речи ?

### ISSUE THREAD

**Issue by xirin1337** [TsSaltan/DevelNext-Windows#9]
Как можно изменить голосовой движок речи при использование Windows::Speak(‘Test’);
Используется стандартный голосовой движок речи , как его изменить на другой ?

**Comment by TsSaltan** [comment]
Можно в настройках Windows выбрать мужской/женский голос
https://support.microsoft.com/ru-ru/help/14199/windows-7-setting-speech-option
